extensions:
  commerce/backend-ui/1:
    $include: ext.config.yaml

application:
  runtimeManifest:
    packages:
      login-module:
        license: Apache-2.0
        actions:
          otp:
            function: actions/otp/otp.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
    database:
      auto-provision: false
      region: apac