operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
runtimeManifest:
  database:
    auto-provision: false
    region: apac
  packages:
    login-module:
      license: Apache-2.0
      actions:
        otp:
          function: actions/otp/otp.js
          web: 'yes'
          runtime: nodejs:22
          inputs:
            LOG_LEVEL: debug
            GRAPHQL_ENDPOINT: $GRAPHQL_ENDPOINT
            DB_TYPE: $DB_TYPE
            MYSQL_HOST: $MYSQL_HOST
            MYSQL_PORT: $MYSQL_PORT
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
          annotations:
            require-adobe-auth: false
            include-ims-credentials: true
            final: false
        config:
          function: actions/config/index.js
          web: 'yes'
          runtime: nodejs:22
          inputs:
            LOG_LEVEL: debug
            apikey: $SERVICE_API_KEY
            DB_TYPE: $DB_TYPE
            MYSQL_HOST: $MYSQL_HOST
            MYSQL_PORT: $MYSQL_PORT
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
          annotations:
            require-adobe-auth: false
            include-ims-credentials: true
            final: true
        customer:
          function: actions/customer/index.js
          web: 'yes'
          runtime: nodejs:22
          inputs:
            LOG_LEVEL: debug
            apikey: $SERVICE_API_KEY
            GRAPHQL_ENDPOINT: $GRAPHQL_ENDPOINT
            DB_TYPE: $DB_TYPE
            MYSQL_HOST: $MYSQL_HOST
            MYSQL_PORT: $MYSQL_PORT
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
          annotations:
            require-adobe-auth: false
            include-ims-credentials: true
            final: true
        registration:
          function: actions/registration/index.js
          web: 'yes'
          runtime: nodejs:22
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: true
            include-ims-credentials: true
            final: true
