operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
runtimeManifest:
  database:
    auto-provision: false
    region: apac
  packages:
    login-module:
      license: Apache-2.0
      actions:
        otp:
          function: actions/otp/otp.js
          web: 'yes'
          runtime: nodejs:22
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: false
            final: false
        config:
          function: actions/config/index.js
          web: 'yes'
          runtime: nodejs:22
          inputs:
            LOG_LEVEL: debug
            apikey: $SERVICE_API_KEY
          annotations:
            require-adobe-auth: true
            include-ims-credentials: true
            final: true
        customer:
          function: actions/customer/index.js
          web: 'yes'
          runtime: nodejs:22
          inputs:
            LOG_LEVEL: debug
            apikey: $SERVICE_API_KEY
            GRAPHQL_ENDPOINT: $GRAPHQL_ENDPOINT
            COMMERCE_GRAPHQL_ENDPOINT: $COMMERCE_GRAPHQL_ENDPOINT
          annotations:
            require-adobe-auth: false
            include-ims-credentials: false
            final: true
        registration:
          function: actions/registration/index.js
          web: 'yes'
          runtime: nodejs:22
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: true
            final: true
